#version 450
#extension GL_ARB_separate_shader_objects : enable

#define WIDTH 3200 * 2
#define HEIGHT 2400 * 2
#define WORKGROUP_SIZE 32
layout(local_size_x = WORKGROUP_SIZE, local_size_y = WORKGROUP_SIZE, local_size_z = 1 ) in;

struct Pixel
{
    vec4 value;
};

layout(std140, binding = 0) buffer buf
{
    Pixel imageData[];
};

void main() 
{
    /* Discard unused threads */
    if(gl_GlobalInvocationID.x >= WIDTH || gl_GlobalInvocationID.y >= HEIGHT)
       return;

    const float x = float(gl_GlobalInvocationID.x) / float(WIDTH);
    const float y = float(gl_GlobalInvocationID.y) / float(HEIGHT);

    vec2 uv = vec2(x,y);
    float n = 0.0;
    vec2 c = vec2(-.445, 0.0) + (uv - 0.5) * (2.0 + 1.7 * 0.2), 
    z = vec2(0.0);

    const int MaxIterations = 10000;
    for (int i = 0; i < MaxIterations; ++i)
    {
         z = vec2(z.x * z.x - z.y * z.y, 2.*z.x * z.y) + c;
         if (dot(z, z) > 256.0) break;
         n++;
    }

    if (n >= float(MaxIterations))
    {
        imageData[WIDTH * gl_GlobalInvocationID.y + gl_GlobalInvocationID.x].value = vec4(0.0, 0.0, 0.0, 1.0);
        return;
    }

    n = n + 1.0 - log2(0.5 * log(dot(z, z)));

    /* https://iquilezles.org/articles/palettes/ */
    float t = fract(n / 32.0);
    vec3 a = vec3(0.5, 0.5, 0.5);
    vec3 b = vec3(0.5, 0.5, 0.5);
    vec3 f = vec3(1.0, 1.0, 1.0);
    vec3 d = vec3(0.263, 0.416, 0.557);
    vec4 color = vec4(a + b * cos(6.28318 * (f * t + d)), 1.0);
      
    imageData[WIDTH * gl_GlobalInvocationID.y + gl_GlobalInvocationID.x].value = color;
}