#!/bin/sh

FILES=$(git diff --cached --name-only --diff-filter=ACMR -- 'src/*.cpp' 'src/*.h' 'include/*.cpp' 'include/*.h')

[ -z "$FILES" ] && exit 0

echo "$FILES" | xargs clang-format --dry-run --Werror
FORMAT_STATUS=$?

if [ $FORMAT_STATUS -ne 0 ]; then
	echo "" >&2
	echo "pre-commit: formatting check failed. Fix with:" >&2
	echo "  clang-format -i $(echo $FILES | tr '\n' ' ')" >&2
	exit $FORMAT_STATUS
fi

echo "$FILES" | xargs clang-tidy --quiet -- -std=c++23 -I.
TIDY_STATUS=$?

if [ $TIDY_STATUS -ne 0 ]; then
	echo "" >&2
	echo "pre-commit: clang-tidy check failed, fix the issues above" >&2
fi

exit $TIDY_STATUS
